<?php

namespace Objects\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RepresentativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentativeRepository extends EntityRepository
{
}
