objects_admin:
    resource: "@ObjectsAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    
# Login routes
login_check:
    path:  /login-check

logout:
    path:  /logout

login:
    path:  /login
    defaults: { _controller: ObjectsAdminBundle:Admin:login }